server.port: 8080

database.host: 592807bd95cd4.gz.cdb.myqcloud.com
database.port: 13773

spring:
  jpa:
    show-sql: true
  datasource:
    password: "root!@#$"
    
login:
  password: hslhc138
    
async.executor.poolSize: 50

access.control.allow.origin: http://139.199.19.176