spring:
  application.name: lhc2
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss      
  liquibase:
    enabled: true
    change-log: classpath:/db/main.xml
  datasource:
    url: jdbc:mysql://${database.host}/${spring.application.name}?useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    tomcat:
      max-wait: -1
      test-on-connect: true
  jpa:
    open-in-view: true

management.endpoints.web.base-path: /manage
    
login:
  account: admin

async.executor.poolSize: 100
