server.port: 9090

common.password: 111111
database.host: localhost
database.port: 3306

spring:
  jpa:
    show-sql: false
  datasource:
    password: ${common.password}
    
login:
  password: ${common.password}
    
async.executor.poolSize: 10

access.control.allow.origin: '*'