--liquibase formatted sql

--changeset lhc2:53

ALTER TABLE `lhc3_times_yz` 
ADD COLUMN `lt12` int(11) NOT NULL,
ADD COLUMN `lt2plus` int(11) NOT NULL,
ADD COLUMN `lt03plus` int(11) NOT NULL,
ADD COLUMN `t12` int(11) NOT NULL,
ADD COLUMN `t2Plus` int(11) NOT NULL,
ADD COLUMN `t03plus` int(11) NOT NULL;

ALTER TABLE `lhc3_color_yz` 
ADD COLUMN `r6color` varchar(50) NOT NULL,
ADD COLUMN `r7color` varchar(50) NOT NULL,
ADD COLUMN `r8color` varchar(50) NOT NULL,
ADD COLUMN `g6color` varchar(50) NOT NULL,
ADD COLUMN `g7color` varchar(50) NOT NULL,
ADD COLUMN `g8color` varchar(50) NOT NULL,
ADD COLUMN `g6` int(11) NOT NULL,
ADD COLUMN `g7` int(11) NOT NULL,
ADD COLUMN `g8` int(11) NOT NULL,
ADD COLUMN `r6` int(11) NOT NULL,
ADD COLUMN `r7` int(11) NOT NULL,
ADD COLUMN `r8` int(11) NOT NULL,
ADD COLUMN `lt_r1` int(11) NOT NULL,
ADD COLUMN `lt_r2` int(11) NOT NULL,
ADD COLUMN `lt_r3` int(11) NOT NULL,
ADD COLUMN `lt_r4` int(11) NOT NULL,
ADD COLUMN `lt_r5` int(11) NOT NULL,
ADD COLUMN `lt_r6` int(11) NOT NULL,
ADD COLUMN `lt_r7` int(11) NOT NULL,
ADD COLUMN `lt_r8` int(11) NOT NULL,
ADD COLUMN `t_r1` int(11) NOT NULL,
ADD COLUMN `t_r2` int(11) NOT NULL,
ADD COLUMN `t_r3` int(11) NOT NULL,
ADD COLUMN `t_r4` int(11) NOT NULL,
ADD COLUMN `t_r5` int(11) NOT NULL,
ADD COLUMN `t_r6` int(11) NOT NULL,
ADD COLUMN `t_r7` int(11) NOT NULL,
ADD COLUMN `t_r8` int(11) NOT NULL,
ADD COLUMN `lt_g1` int(11) NOT NULL,
ADD COLUMN `lt_g2` int(11) NOT NULL,
ADD COLUMN `lt_g3` int(11) NOT NULL,
ADD COLUMN `lt_g4` int(11) NOT NULL,
ADD COLUMN `lt_g5` int(11) NOT NULL,
ADD COLUMN `lt_g6` int(11) NOT NULL,
ADD COLUMN `lt_g7` int(11) NOT NULL,
ADD COLUMN `lt_g8` int(11) NOT NULL,
ADD COLUMN `t_g1` int(11) NOT NULL,
ADD COLUMN `t_g2` int(11) NOT NULL,
ADD COLUMN `t_g3` int(11) NOT NULL,
ADD COLUMN `t_g4` int(11) NOT NULL,
ADD COLUMN `t_g5` int(11) NOT NULL,
ADD COLUMN `t_g6` int(11) NOT NULL,
ADD COLUMN `t_g7` int(11) NOT NULL,
ADD COLUMN `t_g8` int(11) NOT NULL;
